#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$repo_root"

fixture_home="$(mktemp -d /tmp/evee-fixture-test.XXXXXX)"
second_fixture_home="$(mktemp -d /tmp/evee-fixture-test.XXXXXX)"
trap 'rm -rf "$fixture_home" "$second_fixture_home"' EXIT

swift run evee-verification-fixture --home "$fixture_home"
swift run evee-verification-fixture --home "$second_fixture_home"

workspace="$fixture_home/Library/Application Support/Evee"
test -f "$workspace/records.json"
test -f "$workspace/settings.json"
test -f "$workspace/Intelligence/dwell-events.json"
test "$(find "$fixture_home" -type f -perm -004 -print | wc -l | tr -d ' ')" = 0

python3 - "$workspace" "$second_fixture_home/Library/Application Support/Evee" <<'PY'
import json
import pathlib
import sys

workspace = pathlib.Path(sys.argv[1])
second_workspace = pathlib.Path(sys.argv[2])
records = json.loads((workspace / "records.json").read_text())["records"]
expected = {
    "10000000-0000-0000-0000-000000000001": "dictation",
    "20000000-0000-0000-0000-000000000002": "meeting",
    "30000000-0000-0000-0000-000000000003": "memo",
}
assert {record["id"]: record["kind"] for record in records} == expected
settings = json.loads((workspace / "settings.json").read_text())["settings"]
assert settings["mcpEnabled"] is True
assert "webhookSecret" not in settings
assert settings["webhookURL"] == ""
assert {record["createdAt"][:10] for record in records} == {"2026-05-28"}
assert all(record["createdAt"].startswith("2026-05-28T11:") for record in records)

def normalized_json(path):
    value = json.loads(path.read_text())
    # Envelope update times are written by persistence internals rather than
    # supplied by the fixture API. Dwell and journal IDs are also generated by
    # those APIs, so they do not describe fixture semantics.
    value.pop("updatedAt", None)
    if path.name in {"dwell-events.json", "journal.json"}:
        for item in value.get("value", []):
            item.pop("id", None)
    return value

first_json = {path.relative_to(workspace): normalized_json(path) for path in workspace.rglob("*.json")}
second_json = {path.relative_to(second_workspace): normalized_json(path) for path in second_workspace.rglob("*.json")}
different_paths = sorted(str(path) for path in set(first_json) | set(second_json) if first_json.get(path) != second_json.get(path))
assert not different_paths, f"fixture JSON differed after normalization: {different_paths}"
journal = first_json[pathlib.Path("Intelligence/journal.json")]["value"]
assert len(journal) == 1
PY
